name: Github Pages
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@master

      - name: checkout backend
        uses: actions/checkout@v2
        with:
          repository: xuanyuw/NetNote
          path: NetNoteRepo
          persist-credentials: false

      - name: checkout  notes
        uses: actions/checkout@v2
        with:
          ref: main
          path: contentRepo
          persist-credentials: false

      - name: cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install & generate
        run: |
          cp -r contentRepo/* NetNoteRepo
          cd NetNoteRepo/NetNote
          npm install
          npm run generate
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_branch: master
          publish_dir: NetNoteRepo/NetNote/dist
